# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!
# Pods for study_iOS

target 'study_iOS' do

	pod 'Masonry'
	pod 'AFNetworking'
	pod 'Toast'
	pod 'FMDB'

  target 'study_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'study_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
